// Dashboard mock data — ticker entries, big board games, sport metadata

export const TICKER_DATA = [
  { sport: '🏈', label: 'KC -3.0', movement: 'down', prev: '-1.5', curr: '-3.0', book: 'DK' },
  { sport: '🏀', label: 'LAL -3.5', movement: 'up', prev: '-4.5', curr: '-3.5', book: 'FD' },
  { sport: '🏀', label: 'NYK ML', movement: 'down', prev: '-170', curr: '-190', book: 'MGM' },
  { sport: '⚾', label: 'NYY/BOS O9', movement: 'up', prev: '9.5', curr: '9.0', book: 'CZR' },
  { sport: '🏒', label: 'FLA -1.5', movement: 'down', prev: 'PK', curr: '-1.5', book: 'DK' },
  { sport: '⚽', label: 'MIA ML', movement: 'up', prev: '-145', curr: '-130', book: 'FD' },
  { sport: '🏀', label: 'GSW/DEN O231', movement: 'down', prev: '228.0', curr: '231.0', book: 'BET' },
  { sport: '🏈', label: 'PHI/DAL U44', movement: 'down', prev: '46.5', curr: '44.0', book: 'DK' },
  { sport: '🏒', label: 'EDM/COL O6.5', movement: 'up', prev: '6.0', curr: '6.5', book: 'MGM' },
  { sport: '🏀', label: 'PHX +2.0', movement: 'up', prev: '+3.5', curr: '+2.0', book: 'CZR' },
  { sport: '🏈', label: 'SF -5.5', movement: 'down', prev: '-4.0', curr: '-5.5', book: 'FD' },
  { sport: '⚾', label: 'LAD ML', movement: 'down', prev: '-175', curr: '-200', book: 'BET' },
]

export const BIG_BOARD_GAMES = [
  {
    sport: 'NFL',
    sportIcon: '🏈',
    home: 'Chiefs',
    away: 'Bills',
    time: 'SUN 4:25 PM',
    spread: 'KC -3.0',
    ml: '-155',
    ou: '48.5',
    tag: 'GAME OF THE WEEK',
    tagColor: 'green',
  },
  {
    sport: 'NBA',
    sportIcon: '🏀',
    home: 'Lakers',
    away: 'Celtics',
    time: 'TODAY 7:30 PM',
    spread: 'LAL -3.5',
    ml: '-165',
    ou: '224.5',
    tag: 'RIVALRY',
    tagColor: 'cyan',
  },
  {
    sport: 'NHL',
    sportIcon: '🏒',
    home: 'Oilers',
    away: 'Avalanche',
    time: 'TODAY 9:00 PM',
    spread: 'EDM -1.5',
    ml: '-145',
    ou: '6.5',
    tag: 'HIGH SCORING',
    tagColor: 'orange',
  },
  {
    sport: 'MLB',
    sportIcon: '⚾',
    home: 'Dodgers',
    away: 'Padres',
    time: 'TODAY 10:10 PM',
    spread: 'LAD -1.5',
    ml: '-200',
    ou: '8.5',
    tag: 'ACE MATCHUP',
    tagColor: 'cyan',
  },
]

export const SPORT_META = {
  nfl: { games: 16, edges: 2, label: 'NFL', icon: '🏈' },
  nba: { games: 12, edges: 4, label: 'NBA', icon: '🏀' },
  mlb: { games: 15, edges: 2, label: 'MLB', icon: '⚾' },
  nhl: { games: 10, edges: 2, label: 'NHL', icon: '🏒' },
  mls: { games: 8,  edges: 1, label: 'MLS', icon: '⚽' },
}
