// Mock data for all 5 sports
// Each entry = a SPECIFIC actionable bet, not a generic game analysis
// This will be replaced with real API + AI data when keys are provided

// Bet market types
export const MARKET_TYPES = {
  SPREAD: { key: 'spread', label: 'Spread', icon: '📊' },
  MONEYLINE: { key: 'moneyline', label: 'Moneyline', icon: '💰' },
  TOTAL: { key: 'total', label: 'Over/Under', icon: '📈' },
  PLAYER_PROP: { key: 'player_prop', label: 'Player Prop', icon: '🎯' },
  FIRST_HALF: { key: 'first_half', label: '1st Half', icon: '⏱️' },
  TEAM_TOTAL: { key: 'team_total', label: 'Team Total', icon: '🏟️' },
  ALT_LINE: { key: 'alt_line', label: 'Alt Line', icon: '🔀' },
}

const MOCK_DATA = {
  nba: [
    {
      id: 'nba-lal-bos-spread',
      matchup: 'Lakers vs Celtics',
      homeTeam: 'Lakers',
      awayTeam: 'Celtics',
      time: 'Today · 7:30 PM ET',
      marketType: 'spread',
      specificBet: 'Lakers -3.5',
      odds: '-110',
      bestBook: 'DraftKings',
      bookComparison: [
        { book: 'DraftKings', line: '-3.5', odds: '-110' },
        { book: 'FanDuel', line: '-3.5', odds: '-112' },
        { book: 'BetMGM', line: '-4', odds: '-105' },
        { book: 'Caesars', line: '-3.5', odds: '-115' },
      ],
      rating: 'BUY',
      confidence: 9,
      units: 3,
      edgePercent: 3.2,
      keyFactors: [
        'Lakers 14-2 at home in last 16 games',
        'LeBron averaging 31.2 PPG in last 5',
        'Celtics missing Kristaps Porzingis (calf)',
        'Sharp money on Lakers — line moved from -2 to -3.5',
      ],
      riskFactors: [
        'Celtics 8-2 in last 10 road games',
        'Back-to-back game for Lakers',
      ],
      reasoning: 'Line is mispriced. Vegas overweighting Boston\'s road record and not adjusting for the Porzingis absence. Lakers\' home dominance is elite. Sharp money movement from -2 to -3.5 confirms value. Public perception gap creates a 3.2% edge.',
      recentForm: ['W', 'W', 'L', 'W', 'W', 'W', 'W', 'L', 'W', 'W'],
    },
    {
      id: 'nba-lal-bos-prop-lebron',
      matchup: 'Lakers vs Celtics',
      homeTeam: 'Lakers',
      awayTeam: 'Celtics',
      time: 'Today · 7:30 PM ET',
      marketType: 'player_prop',
      specificBet: 'LeBron James Over 28.5 Points',
      odds: '-115',
      bestBook: 'FanDuel',
      bookComparison: [
        { book: 'FanDuel', line: '28.5', odds: '-115' },
        { book: 'DraftKings', line: '29.5', odds: '-105' },
        { book: 'BetMGM', line: '28.5', odds: '-120' },
      ],
      rating: 'BUY',
      confidence: 8,
      units: 2,
      edgePercent: 4.1,
      keyFactors: [
        'LeBron averaging 31.2 PPG in last 5 games',
        'Celtics allowing 118.4 PPG without Porzingis rim protection',
        'LeBron has hit Over 28.5 in 7 of last 9 home games',
        'Rivalry game — LeBron historically averages 32.1 PPG vs BOS',
      ],
      riskFactors: [
        'LeBron could sit 4th quarter in a blowout',
        'Minutes managed on back-to-backs sometimes',
      ],
      reasoning: 'FanDuel has the best line at 28.5 vs DraftKings at 29.5. Without Porzingis as the rim protector, LeBron will attack the paint relentlessly. His rivalry usage rate vs Boston is historically 34.2% — elite volume. This line should be 30.5.',
      recentForm: ['W', 'W', 'L', 'W', 'W', 'W', 'W', 'L', 'W', 'W'],
    },
    {
      id: 'nba-gsw-den-total',
      matchup: 'Warriors vs Nuggets',
      homeTeam: 'Warriors',
      awayTeam: 'Nuggets',
      time: 'Today · 10:00 PM ET',
      marketType: 'total',
      specificBet: 'Over 231.0',
      odds: '-110',
      bestBook: 'BetMGM',
      bookComparison: [
        { book: 'BetMGM', line: '231.0', odds: '-110' },
        { book: 'DraftKings', line: '231.5', odds: '-110' },
        { book: 'FanDuel', line: '231.0', odds: '-115' },
      ],
      rating: 'BUY',
      confidence: 7,
      units: 1,
      edgePercent: 2.4,
      keyFactors: [
        'Both teams top 5 in pace this month',
        'Last 4 H2H games averaged 238 total points',
        'Warriors\' defensive rating dropped to 114.8 without Draymond',
      ],
      riskFactors: [
        'Jokic questionable with ankle soreness',
        'Warriors home games trend under this season (55%)',
      ],
      reasoning: 'Pace-driven play. Without Draymond, Golden State can\'t slow the game. Denver pushes tempo with Jokic in transition. The 231 feels about 4 points low based on recent pace data and defensive gaps.',
      recentForm: ['W', 'L', 'W', 'L', 'W', 'L', 'W', 'W', 'L', 'W'],
    },
    {
      id: 'nba-gsw-den-prop-jokic',
      matchup: 'Warriors vs Nuggets',
      homeTeam: 'Warriors',
      awayTeam: 'Nuggets',
      time: 'Today · 10:00 PM ET',
      marketType: 'player_prop',
      specificBet: 'Nikola Jokic Over 11.5 Rebounds',
      odds: '-120',
      bestBook: 'DraftKings',
      bookComparison: [
        { book: 'DraftKings', line: '11.5', odds: '-120' },
        { book: 'FanDuel', line: '12.5', odds: '+105' },
        { book: 'BetMGM', line: '11.5', odds: '-125' },
      ],
      rating: 'BUY',
      confidence: 7,
      units: 1,
      edgePercent: 2.8,
      keyFactors: [
        'Jokic averaging 14.2 RPG in last 8 games',
        'Warriors\' rebounding rank: 28th in the NBA',
        'High-paced game = more misses = more rebound opportunities',
      ],
      riskFactors: [
        'Jokic questionable — could get limited minutes',
        'Kevon Looney sometimes holds Jokic in check on boards',
      ],
      reasoning: 'The Warriors are terrible on the glass and this game projects to be fast-paced with a lot of misses. Jokic has cleared 11.5 rebounds in 9 of his last 11 games. DraftKings line is a full rebound lower than FanDuel — clear value.',
      recentForm: ['W', 'L', 'W', 'L', 'W', 'L', 'W', 'W', 'L', 'W'],
    },
    {
      id: 'nba-mil-mia-1h',
      matchup: 'Bucks vs Heat',
      homeTeam: 'Bucks',
      awayTeam: 'Heat',
      time: 'Today · 8:00 PM ET',
      marketType: 'first_half',
      specificBet: 'Bucks 1H Spread -4.0',
      odds: '-110',
      bestBook: 'FanDuel',
      bookComparison: [
        { book: 'FanDuel', line: '-4.0', odds: '-110' },
        { book: 'DraftKings', line: '-3.5', odds: '-115' },
        { book: 'BetMGM', line: '-4.0', odds: '-112' },
      ],
      rating: 'BYE',
      confidence: 3,
      units: 0,
      edgePercent: 0,
      keyFactors: [
        'Heat historically competitive in 1st halves at Milwaukee',
      ],
      riskFactors: [
        'Giannis 35 PPG in last 5 vs MIA',
        'Heat missing Jimmy Butler (suspension)',
        'Line movement suggests sharps on Bucks full game, not 1H',
        'No clear edge on 1H number',
      ],
      reasoning: 'Butler absence makes this look tempting, but the 1H spread already prices in the news. Milwaukee tends to start slow at home and dominate 3rd quarters. The full game might be a better spot, but even that has limited edge at -6.5. Stay away.',
      recentForm: ['W', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'W'],
    },
    {
      id: 'nba-nyk-phi-ml',
      matchup: 'Knicks vs Sixers',
      homeTeam: 'Knicks',
      awayTeam: 'Sixers',
      time: 'Today · 7:00 PM ET',
      marketType: 'moneyline',
      specificBet: 'Knicks ML',
      odds: '-190',
      bestBook: 'DraftKings',
      bookComparison: [
        { book: 'DraftKings', line: 'ML', odds: '-190' },
        { book: 'FanDuel', line: 'ML', odds: '-195' },
        { book: 'Caesars', line: 'ML', odds: '-185' },
      ],
      rating: 'BUY',
      confidence: 8,
      units: 2,
      edgePercent: 3.5,
      keyFactors: [
        'Knicks 18-3 at MSG this season',
        'Embiid out — Sixers offensive rating drops 12 points without him',
        'Brunson averaging 28.5 PPG at home',
        'Knicks defense ranked #2 at home',
      ],
      riskFactors: [
        'Sixers covered in 3 of last 4 visits to MSG',
        'Knicks sometimes play down to competition',
      ],
      reasoning: 'Without Embiid, Philly has no rim protection answer for the Knicks\' paint attack. Brunson at MSG is automatic. ML is safer than the spread here — Knicks should win by 8+. Caesars has the best price at -185.',
      recentForm: ['W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'L', 'W'],
    },
    {
      id: 'nba-nyk-phi-teamtotal',
      matchup: 'Knicks vs Sixers',
      homeTeam: 'Knicks',
      awayTeam: 'Sixers',
      time: 'Today · 7:00 PM ET',
      marketType: 'team_total',
      specificBet: 'Sixers Team Total Under 101.5',
      odds: '-115',
      bestBook: 'BetMGM',
      bookComparison: [
        { book: 'BetMGM', line: 'U 101.5', odds: '-115' },
        { book: 'DraftKings', line: 'U 102.5', odds: '-110' },
        { book: 'FanDuel', line: 'U 101.5', odds: '-118' },
      ],
      rating: 'BUY',
      confidence: 7,
      units: 1,
      edgePercent: 2.9,
      keyFactors: [
        'Sixers averaging 96.3 PPG without Embiid this season',
        'Knicks home defense allowing 102.1 PPG — elite',
        'No Embiid means 8 fewer paint points per game',
      ],
      riskFactors: [
        'Tyrese Maxey can explode for 35+ on any night',
        'If Knicks build a big lead, bench units could soften this',
      ],
      reasoning: 'Without their MVP candidate, the Sixers offense craters. They\'ve averaged 96.3 PPG in games Embiid has missed and the Knicks\' home defense is among the league\'s best. This line should be 99.5. DraftKings at U 102.5 is even better if you can get it.',
      recentForm: ['W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'L', 'W'],
    },
    {
      id: 'nba-phx-dal-spread',
      matchup: 'Suns vs Mavericks',
      homeTeam: 'Suns',
      awayTeam: 'Mavericks',
      time: 'Today · 9:30 PM ET',
      marketType: 'spread',
      specificBet: 'Suns +2.0',
      odds: '-110',
      bestBook: 'FanDuel',
      bookComparison: [
        { book: 'FanDuel', line: '+2.0', odds: '-110' },
        { book: 'DraftKings', line: '+1.5', odds: '-110' },
        { book: 'BetMGM', line: '+2.0', odds: '-112' },
      ],
      rating: 'BUY',
      confidence: 6,
      units: 1,
      edgePercent: 1.8,
      keyFactors: [
        'Booker shooting 52% from 3 in last 7 games',
        'Suns 5-1 ATS at home as underdogs this year',
      ],
      riskFactors: [
        'Luka Doncic averaging a triple-double in last 10',
        'Suns defensive rating worst in the West',
        'Dallas 4-1 in last 5 H2H',
      ],
      reasoning: 'Getting Booker at home as a dog is always interesting. The Suns\' ATS record as home underdogs suggests the market over-discounts them. Edge is narrow — 1 unit max.',
      recentForm: ['L', 'W', 'W', 'L', 'L', 'W', 'W', 'L', 'W', 'L'],
    },
    {
      id: 'nba-lac-okc-spread',
      matchup: 'Clippers vs Thunder',
      homeTeam: 'Clippers',
      awayTeam: 'Thunder',
      time: 'Today · 10:30 PM ET',
      marketType: 'spread',
      specificBet: 'Thunder -8.5',
      odds: '-110',
      bestBook: 'Caesars',
      bookComparison: [
        { book: 'Caesars', line: '-8.5', odds: '-110' },
        { book: 'DraftKings', line: '-8.5', odds: '-110' },
        { book: 'FanDuel', line: '-9.0', odds: '-108' },
      ],
      rating: 'BYE',
      confidence: 2,
      units: 0,
      edgePercent: 0,
      keyFactors: [],
      riskFactors: [
        'SGA could rest on back-to-back — monitor',
        'Clippers tanking end of season',
        'Blowout risk makes spread volatile',
        'No edge — line is accurate',
      ],
      reasoning: 'Line is set correctly. OKC should dominate but 8.5 is the right number. Possible SGA rest makes this unpredictable. Stay away.',
      recentForm: ['L', 'L', 'W', 'L', 'L', 'L', 'W', 'L', 'L', 'L'],
    },
  ],
  nfl: [
    {
      id: 'nfl-kc-buf-spread',
      matchup: 'Chiefs vs Bills',
      homeTeam: 'Chiefs',
      awayTeam: 'Bills',
      time: 'Sunday · 4:25 PM ET',
      marketType: 'spread',
      specificBet: 'Chiefs -3.0',
      odds: '-110',
      bestBook: 'DraftKings',
      bookComparison: [
        { book: 'DraftKings', line: '-3.0', odds: '-110' },
        { book: 'FanDuel', line: '-3.0', odds: '-112' },
        { book: 'BetMGM', line: '-2.5', odds: '-115' },
      ],
      rating: 'BUY',
      confidence: 8,
      units: 2,
      edgePercent: 3.1,
      keyFactors: [
        'Mahomes 14-3 at Arrowhead in playoffs-caliber games',
        'Bills 2-8 ATS as road dogs vs KC',
        'KC defense allowing 14.2 PPG at home last 6 weeks',
        'Sharp money moved line from -1.5 to -3',
      ],
      riskFactors: [
        'Josh Allen 4 TDs in last meeting',
        'Bills offense ranked #1 in DVOA',
      ],
      reasoning: 'Arrowhead advantage is real. Line opened at -1.5 and sharp money hammered it to -3. Mahomes at home in big games is an ATM. Bills have a Josh Allen problem in KC.',
      recentForm: ['W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'L'],
    },
    {
      id: 'nfl-kc-buf-prop-mahomes',
      matchup: 'Chiefs vs Bills',
      homeTeam: 'Chiefs',
      awayTeam: 'Bills',
      time: 'Sunday · 4:25 PM ET',
      marketType: 'player_prop',
      specificBet: 'Patrick Mahomes Over 274.5 Pass Yds',
      odds: '-110',
      bestBook: 'FanDuel',
      bookComparison: [
        { book: 'FanDuel', line: '274.5', odds: '-110' },
        { book: 'DraftKings', line: '279.5', odds: '-105' },
        { book: 'BetMGM', line: '276.5', odds: '-110' },
      ],
      rating: 'BUY',
      confidence: 7,
      units: 1,
      edgePercent: 2.6,
      keyFactors: [
        'Mahomes averaging 298 pass yds at home this season',
        'Bills secondary allowing 265 pass yds/game on the road',
        'Game script: Chiefs likely playing from ahead = sustained passing',
        'Kelce historically feasts in this matchup — opens up deep game',
      ],
      riskFactors: [
        'Chiefs may lean on run game if they build early lead',
        'Weather: check for wind at Arrowhead',
      ],
      reasoning: 'FanDuel has a full 5 yards lower than DraftKings at 274.5 vs 279.5. In games at Arrowhead against playoff-caliber opponents, Mahomes averages 298 yards. The Bills\' secondary is vulnerable on the road. This is a prop shop — take the best number.',
      recentForm: ['W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W', 'L'],
    },
    {
      id: 'nfl-phi-dal-total',
      matchup: 'Eagles vs Cowboys',
      homeTeam: 'Eagles',
      awayTeam: 'Cowboys',
      time: 'Sunday · 1:00 PM ET',
      marketType: 'total',
      specificBet: 'Under 44.0',
      odds: '-110',
      bestBook: 'BetMGM',
      bookComparison: [
        { book: 'BetMGM', line: 'U 44.0', odds: '-110' },
        { book: 'FanDuel', line: 'U 43.5', odds: '-110' },
        { book: 'DraftKings', line: 'U 44.0', odds: '-112' },
      ],
      rating: 'BUY',
      confidence: 10,
      units: 5,
      edgePercent: 6.8,
      keyFactors: [
        '🏠 MORTGAGE PLAY — Last 8 PHI/DAL games averaged 38.5 total',
        'Eagles D allowing 13.8 PPG at home',
        'Cowboys offense bottom 5 in red zone conversion (42%)',
        'Weather: 34°F, 15mph winds at Lincoln Financial',
        'Under is 7-1 in last 8 NFC East divisional games here',
      ],
      riskFactors: [
        'CeeDee Lamb big play potential could spike total',
      ],
      reasoning: 'Best spot on the board. Cold weather, elite defense, and a Cowboys offense that can\'t finish drives. The 44 is too high — should be 40.5. Wind alone knocks 3-4 points off. Hammer the under.',
      recentForm: ['W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W'],
    },
    {
      id: 'nfl-phi-dal-1h-spread',
      matchup: 'Eagles vs Cowboys',
      homeTeam: 'Eagles',
      awayTeam: 'Cowboys',
      time: 'Sunday · 1:00 PM ET',
      marketType: 'first_half',
      specificBet: 'Eagles 1H Spread -4.0',
      odds: '-105',
      bestBook: 'Caesars',
      bookComparison: [
        { book: 'Caesars', line: '-4.0', odds: '-105' },
        { book: 'DraftKings', line: '-3.5', odds: '-110' },
        { book: 'FanDuel', line: '-4.0', odds: '-108' },
      ],
      rating: 'BUY',
      confidence: 8,
      units: 2,
      edgePercent: 3.4,
      keyFactors: [
        'Eagles 1H scoring average: 17.2 PPG at home',
        'Cowboys 1H road scoring average: 8.4 PPG',
        'Dallas starts slow — scored 3 or fewer 1H points in 5 of last 8 road games',
        'Saquon Barkley averaging 85 rush yds in 1st halves',
      ],
      riskFactors: [
        'NFC East games tend to start tight',
      ],
      reasoning: 'Dallas is a different team in the 1st half on the road — they can\'t get going. Eagles come out aggressive with Barkley and the 1H spread is actually a better play than the full game -7 spread. The Cowboys\' 1H road scoring is historically awful.',
      recentForm: ['W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W'],
    },
    {
      id: 'nfl-sf-sea-spread',
      matchup: '49ers vs Seahawks',
      homeTeam: '49ers',
      awayTeam: 'Seahawks',
      time: 'Sunday · 4:05 PM ET',
      marketType: 'spread',
      specificBet: '49ers -5.5',
      odds: '-110',
      bestBook: 'FanDuel',
      bookComparison: [
        { book: 'FanDuel', line: '-5.5', odds: '-110' },
        { book: 'DraftKings', line: '-5.5', odds: '-110' },
        { book: 'BetMGM', line: '-6.0', odds: '-105' },
      ],
      rating: 'BYE',
      confidence: 4,
      units: 0,
      edgePercent: 0,
      keyFactors: [
        'CMC questionable — changes everything',
      ],
      riskFactors: [
        'Seahawks 5-2 ATS as road dogs this year',
        'CMC status unknown — line could move 2 pts either way',
        'Divisional games trend closer than lines suggest',
      ],
      reasoning: 'Can\'t bet this until CMC status is confirmed. If he plays, it\'s a 7-point game. If he sits, Seattle covers easily. Too much variance.',
      recentForm: ['W', 'L', 'W', 'W', 'W', 'L', 'W', 'W', 'L', 'W'],
    },
    {
      id: 'nfl-phi-dal-prop-lamb',
      matchup: 'Eagles vs Cowboys',
      homeTeam: 'Eagles',
      awayTeam: 'Cowboys',
      time: 'Sunday · 1:00 PM ET',
      marketType: 'player_prop',
      specificBet: 'CeeDee Lamb Under 72.5 Rec Yds',
      odds: '-110',
      bestBook: 'DraftKings',
      bookComparison: [
        { book: 'DraftKings', line: 'U 72.5', odds: '-110' },
        { book: 'FanDuel', line: 'U 74.5', odds: '-112' },
        { book: 'BetMGM', line: 'U 72.5', odds: '-115' },
      ],
      rating: 'BUY',
      confidence: 7,
      units: 1,
      edgePercent: 2.5,
      keyFactors: [
        'Slay + Bradberry have held top WRs under 60 yds in 6 of 8 games',
        'Wind at 15mph reduces deep ball accuracy by ~18%',
        'Lamb averaging 58 yds vs top-10 pass defenses this season',
      ],
      riskFactors: [
        'Lamb is a YAC monster — needs only 3-4 catches to hit',
        'Eagles may focus on stopping the run, leaving 1v1s for Lamb',
      ],
      reasoning: 'This pairs perfectly with the Under 44 game total. If the total stays low, someone\'s getting shut down — and Lamb vs this Eagles secondary in cold wind is a nightmare. His splits vs top defenses tell the story.',
      recentForm: ['W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W'],
    },
  ],
  mlb: [
    {
      id: 'mlb-nyy-bos-rl',
      matchup: 'Yankees vs Red Sox',
      homeTeam: 'Yankees',
      awayTeam: 'Red Sox',
      time: 'Today · 7:05 PM ET',
      marketType: 'spread',
      specificBet: 'Yankees -1.5 (Run Line)',
      odds: '+130',
      bestBook: 'DraftKings',
      bookComparison: [
        { book: 'DraftKings', line: '-1.5', odds: '+130' },
        { book: 'FanDuel', line: '-1.5', odds: '+125' },
        { book: 'BetMGM', line: '-1.5', odds: '+128' },
      ],
      rating: 'BUY',
      confidence: 7,
      units: 1,
      edgePercent: 2.3,
      keyFactors: [
        'Cole pitching: 2.1 ERA in last 6 starts',
        'Red Sox starter has 5.8 ERA on the road',
        'Yankees bullpen leads AL in WAR',
        'Judge 5 HR in last 8 games vs BOS',
      ],
      riskFactors: [
        'Rivalry games tend to be tighter',
        'Red Sox have hit Cole historically (.285 BA)',
      ],
      reasoning: 'Cole at Yankee Stadium against a struggling road starter is a pillar play. The bullpen advantage seals late leads. Run line at +130 offers value when win probability is ~68%.',
      recentForm: ['W', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'W', 'L'],
    },
    {
      id: 'mlb-nyy-bos-prop-judge',
      matchup: 'Yankees vs Red Sox',
      homeTeam: 'Yankees',
      awayTeam: 'Red Sox',
      time: 'Today · 7:05 PM ET',
      marketType: 'player_prop',
      specificBet: 'Aaron Judge Over 1.5 Total Bases',
      odds: '-130',
      bestBook: 'FanDuel',
      bookComparison: [
        { book: 'FanDuel', line: 'O 1.5', odds: '-130' },
        { book: 'DraftKings', line: 'O 1.5', odds: '-135' },
        { book: 'BetMGM', line: 'O 1.5', odds: '-128' },
      ],
      rating: 'BUY',
      confidence: 8,
      units: 2,
      edgePercent: 3.8,
      keyFactors: [
        'Judge slugging .720 at home this month',
        '5 HR in last 8 games vs BOS',
        'Red Sox starter gives up 2.1 HR/9 on the road',
        'Short porch in right favors Judge\'s pull power',
      ],
      riskFactors: [
        'Judge 0-5 in one game vs this pitcher last year',
      ],
      reasoning: 'Judge only needs a double or HR to clear 1.5 total bases. Against a fly-ball pitcher with a 2.1 HR/9 road rate, in the short porch? The math says this hits 72% of the time. Line should be -150.',
      recentForm: ['W', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'W', 'L'],
    },
    {
      id: 'mlb-lad-sd-ml',
      matchup: 'Dodgers vs Padres',
      homeTeam: 'Dodgers',
      awayTeam: 'Padres',
      time: 'Today · 10:10 PM ET',
      marketType: 'moneyline',
      specificBet: 'Dodgers ML',
      odds: '-200',
      bestBook: 'Caesars',
      bookComparison: [
        { book: 'Caesars', line: 'ML', odds: '-195' },
        { book: 'DraftKings', line: 'ML', odds: '-200' },
        { book: 'FanDuel', line: 'ML', odds: '-205' },
      ],
      rating: 'BUY',
      confidence: 8,
      units: 2,
      edgePercent: 2.7,
      keyFactors: [
        'Ohtani 8-for-14 with 3 HR lifetime vs Padres starter',
        'Dodgers 12-2 at home this month',
        'NL-best run differential (+87)',
        'Padres bullpen 5.2 ERA in last 2 weeks',
      ],
      riskFactors: [
        'Machado always shows up vs LAD',
        'Juice on ML is steep (-200)',
      ],
      reasoning: 'Ohtani owns this pitcher. Dodgers\' run differential says they\'re the real deal at home. Padres bullpen is crumbling — any lead past 6th is safe. Caesars has best price at -195.',
      recentForm: ['W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W'],
    },
    {
      id: 'mlb-lad-sd-f5',
      matchup: 'Dodgers vs Padres',
      homeTeam: 'Dodgers',
      awayTeam: 'Padres',
      time: 'Today · 10:10 PM ET',
      marketType: 'first_half',
      specificBet: 'Dodgers F5 -0.5 (First 5 Innings)',
      odds: '-140',
      bestBook: 'DraftKings',
      bookComparison: [
        { book: 'DraftKings', line: '-0.5', odds: '-140' },
        { book: 'FanDuel', line: '-0.5', odds: '-145' },
        { book: 'BetMGM', line: '-0.5', odds: '-142' },
      ],
      rating: 'BUY',
      confidence: 7,
      units: 1,
      edgePercent: 2.2,
      keyFactors: [
        'Dodgers starter has 1.8 ERA through 5 innings this month',
        'Padres starter allows 4.2 runs through 5 innings on the road',
        'Isolates the bet from the shaky Padres bullpen variable',
      ],
      riskFactors: [
        'Padres lineup is dangerous 1st time through the order',
      ],
      reasoning: 'F5 (first 5 inning) line eliminates bullpen variance entirely. This is a starter-vs-starter bet and the Dodgers\' ace is pitching at an elite level. Pairs well with the full game ML but limits exposure.',
      recentForm: ['W', 'W', 'W', 'W', 'L', 'W', 'W', 'W', 'W', 'W'],
    },
  ],
  nhl: [
    {
      id: 'nhl-fla-nyr-pl',
      matchup: 'Panthers vs Rangers',
      homeTeam: 'Panthers',
      awayTeam: 'Rangers',
      time: 'Today · 7:00 PM ET',
      marketType: 'spread',
      specificBet: 'Panthers -1.5 (Puck Line)',
      odds: '+165',
      bestBook: 'DraftKings',
      bookComparison: [
        { book: 'DraftKings', line: '-1.5', odds: '+165' },
        { book: 'FanDuel', line: '-1.5', odds: '+160' },
        { book: 'BetMGM', line: '-1.5', odds: '+155' },
      ],
      rating: 'BUY',
      confidence: 7,
      units: 1,
      edgePercent: 2.5,
      keyFactors: [
        'Bobrovsky .938 SV% in last 8 starts',
        'Panthers power play clicking at 32%',
        'Rangers lost 4 of last 6 on the road',
      ],
      riskFactors: [
        'Rangers play tight games vs FLA historically',
        'Shesterkin can steal any game',
      ],
      reasoning: 'Bob is in Vezina form and the PP is lethal. Rangers\' road struggles make the puck line viable at plus money. DraftKings has +165 vs FanDuel at +160.',
      recentForm: ['W', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'W'],
    },
    {
      id: 'nhl-edm-col-total',
      matchup: 'Oilers vs Avalanche',
      homeTeam: 'Oilers',
      awayTeam: 'Avalanche',
      time: 'Today · 9:00 PM ET',
      marketType: 'total',
      specificBet: 'Over 6.5 Goals',
      odds: '-115',
      bestBook: 'FanDuel',
      bookComparison: [
        { book: 'FanDuel', line: 'O 6.5', odds: '-115' },
        { book: 'DraftKings', line: 'O 6.5', odds: '-118' },
        { book: 'BetMGM', line: 'O 6.5', odds: '-112' },
      ],
      rating: 'BUY',
      confidence: 9,
      units: 3,
      edgePercent: 4.5,
      keyFactors: [
        'McDavid + Draisaitl combining for 5.2 pts/game last 10',
        'MacKinnon on a 12-game point streak',
        'Last 5 H2H averaged 7.4 goals',
        'Both teams bottom 10 in goaltending last 2 weeks',
      ],
      riskFactors: [
        'Oilers could start backup goalie',
      ],
      reasoning: 'When these two play, the net bulges. Both goaltending situations are shaky, and you have 4 of the best offensive players on the planet. The 6.5 is begging to go over. BetMGM has the best juice at -112.',
      recentForm: ['W', 'W', 'L', 'W', 'W', 'W', 'W', 'L', 'W', 'W'],
    },
    {
      id: 'nhl-edm-col-prop-mcdavid',
      matchup: 'Oilers vs Avalanche',
      homeTeam: 'Oilers',
      awayTeam: 'Avalanche',
      time: 'Today · 9:00 PM ET',
      marketType: 'player_prop',
      specificBet: 'Connor McDavid Over 0.5 Goals (Anytime Scorer)',
      odds: '-135',
      bestBook: 'BetMGM',
      bookComparison: [
        { book: 'BetMGM', line: 'ATG', odds: '-135' },
        { book: 'DraftKings', line: 'ATG', odds: '-140' },
        { book: 'FanDuel', line: 'ATG', odds: '-138' },
      ],
      rating: 'BUY',
      confidence: 8,
      units: 2,
      edgePercent: 3.3,
      keyFactors: [
        'McDavid has scored in 8 of last 10 games',
        'Avalanche backup goalie expected to start (.891 SV%)',
        'McDavid has 6 goals in last 4 games vs COL',
        'High-scoring game environment boosts goal probability',
      ],
      riskFactors: [
        'McDavid sometimes defers to Draisaitl in these matchups',
      ],
      reasoning: 'McDavid vs a backup goalie in a game that projects 7+ goals? He\'s scored in 8 of 10 and historically dominates Colorado. This is one of the safest props on the board tonight.',
      recentForm: ['W', 'W', 'L', 'W', 'W', 'W', 'W', 'L', 'W', 'W'],
    },
    {
      id: 'nhl-fla-nyr-prop-barkov',
      matchup: 'Panthers vs Rangers',
      homeTeam: 'Panthers',
      awayTeam: 'Rangers',
      time: 'Today · 7:00 PM ET',
      marketType: 'player_prop',
      specificBet: 'Aleksander Barkov Over 2.5 SOG (Shots on Goal)',
      odds: '-120',
      bestBook: 'FanDuel',
      bookComparison: [
        { book: 'FanDuel', line: 'O 2.5', odds: '-120' },
        { book: 'DraftKings', line: 'O 2.5', odds: '-125' },
        { book: 'BetMGM', line: 'O 3.5', odds: '+130' },
      ],
      rating: 'BUY',
      confidence: 6,
      units: 1,
      edgePercent: 1.9,
      keyFactors: [
        'Barkov averaging 3.8 SOG at home this month',
        'Rangers allowing 33+ SOG per game on the road',
        'Barkov plays 22+ min and gets PP time',
      ],
      riskFactors: [
        'Could get matched against Trouba who limits shooting lanes',
        'Tight game = fewer shot attempts for everyone',
      ],
      reasoning: 'Barkov\'s shot volume at home has been elite (3.8/game this month). Rangers are one of the worst at limiting shots to opposing top-6 forwards on the road. Lean play — 1 unit.',
      recentForm: ['W', 'W', 'W', 'L', 'W', 'W', 'L', 'W', 'W', 'W'],
    },
  ],
  mls: [
    {
      id: 'mls-mia-lafc-ml',
      matchup: 'Inter Miami vs LAFC',
      homeTeam: 'Inter Miami',
      awayTeam: 'LAFC',
      time: 'Saturday · 8:00 PM ET',
      marketType: 'moneyline',
      specificBet: 'Inter Miami ML',
      odds: '-130',
      bestBook: 'DraftKings',
      bookComparison: [
        { book: 'DraftKings', line: 'ML', odds: '-130' },
        { book: 'FanDuel', line: 'ML', odds: '-135' },
        { book: 'BetMGM', line: 'ML', odds: '-128' },
      ],
      rating: 'BUY',
      confidence: 7,
      units: 1,
      edgePercent: 2.1,
      keyFactors: [
        'Messi has 6 goals in last 4 home matches',
        'Inter Miami unbeaten at home in 2024 (9-0-2)',
        'LAFC coming off midweek CCL match — fatigue factor',
      ],
      riskFactors: [
        'LAFC historically strong in big away games',
        'MLS parity makes any match volatile',
      ],
      reasoning: 'Messi at home vs a fatigued LAFC is a clear value play. The -130 doesn\'t fully price in the midweek fatigue. BetMGM has the best line at -128.',
      recentForm: ['W', 'W', 'D', 'W', 'W', 'L', 'W', 'W', 'D', 'W'],
    },
    {
      id: 'mls-mia-lafc-prop-messi',
      matchup: 'Inter Miami vs LAFC',
      homeTeam: 'Inter Miami',
      awayTeam: 'LAFC',
      time: 'Saturday · 8:00 PM ET',
      marketType: 'player_prop',
      specificBet: 'Lionel Messi Over 2.5 Shots on Target',
      odds: '+110',
      bestBook: 'FanDuel',
      bookComparison: [
        { book: 'FanDuel', line: 'O 2.5', odds: '+110' },
        { book: 'DraftKings', line: 'O 2.5', odds: '+105' },
        { book: 'BetMGM', line: 'O 2.5', odds: '+100' },
      ],
      rating: 'BUY',
      confidence: 7,
      units: 1,
      edgePercent: 2.4,
      keyFactors: [
        'Messi averaging 3.2 SOT per home game this season',
        'LAFC keeper has .72 save % — leaks shots through',
        'Plus money on a high-volume shooter at home',
      ],
      riskFactors: [
        'Messi sometimes takes more of a playmaker role',
        'Could be subbed off after 70 minutes',
      ],
      reasoning: 'Getting Messi SOT at plus money is rare. He\'s averaging 3.2 at home and LAFC\'s keeper gives up shots. This is a volume play with positive EV.',
      recentForm: ['W', 'W', 'D', 'W', 'W', 'L', 'W', 'W', 'D', 'W'],
    },
    {
      id: 'mls-atl-nyc-total',
      matchup: 'Atlanta United vs NYCFC',
      homeTeam: 'Atlanta United',
      awayTeam: 'NYCFC',
      time: 'Saturday · 7:30 PM ET',
      marketType: 'total',
      specificBet: 'Under 2.5 Goals',
      odds: '-105',
      bestBook: 'BetMGM',
      bookComparison: [
        { book: 'BetMGM', line: 'U 2.5', odds: '-105' },
        { book: 'DraftKings', line: 'U 2.5', odds: '-108' },
        { book: 'FanDuel', line: 'U 2.5', odds: '-110' },
      ],
      rating: 'BUY',
      confidence: 6,
      units: 1,
      edgePercent: 1.7,
      keyFactors: [
        'Atlanta defense: 5 clean sheets in last 8 home games',
        'NYCFC averaging 0.8 goals on the road',
        'Under has hit in 6 of last 8 ATL home games',
      ],
      riskFactors: [
        'Atlanta\'s attack can explode',
        'Small sample size on NYCFC road stats',
      ],
      reasoning: 'Both teams defend well and struggle in the final third on the road. Atlanta\'s clean sheet rate and NYCFC\'s poor road scoring make the under the smart play. BetMGM has -105 vs FanDuel at -110.',
      recentForm: ['W', 'L', 'D', 'W', 'L', 'W', 'L', 'D', 'W', 'L'],
    },
    {
      id: 'mls-atl-nyc-1h',
      matchup: 'Atlanta United vs NYCFC',
      homeTeam: 'Atlanta United',
      awayTeam: 'NYCFC',
      time: 'Saturday · 7:30 PM ET',
      marketType: 'first_half',
      specificBet: '1st Half Under 1.5 Goals',
      odds: '-110',
      bestBook: 'DraftKings',
      bookComparison: [
        { book: 'DraftKings', line: '1H U 1.5', odds: '-110' },
        { book: 'FanDuel', line: '1H U 1.5', odds: '-115' },
      ],
      rating: 'BUY',
      confidence: 6,
      units: 1,
      edgePercent: 1.5,
      keyFactors: [
        'Atlanta 1st half home games average 0.7 total goals',
        'NYCFC hasn\'t scored a 1st half road goal in 4 games',
      ],
      riskFactors: [
        'One early goal could still push over 1.5',
        'Limited book comparison available',
      ],
      reasoning: 'Pairs with the full game under thesis. These teams sleepwalk through first halves on the road. 1H Under 1.5 has hit in 7 of Atlanta\'s last 9 home games.',
      recentForm: ['W', 'L', 'D', 'W', 'L', 'W', 'L', 'D', 'W', 'L'],
    },
  ],
}

// Simulated terminal logs for the pipeline
const PIPELINE_LOGS = {
  scrape: [
    { time: '00:00', message: 'Initializing multi-market odds scraper...', type: '' },
    { time: '00:01', message: 'Connecting to The Odds API v4...', type: 'highlight' },
    { time: '00:02', message: 'Fetching h2h, spreads, totals, outrights...', type: '' },
    { time: '00:03', message: 'Found {count} active betting markets across {games} games', type: 'highlight' },
    { time: '00:04', message: 'Scraping DraftKings player props via Firecrawl...', type: '' },
    { time: '00:06', message: 'Scraping FanDuel alternate lines & 1st half markets...', type: '' },
    { time: '00:08', message: 'Cross-referencing odds across 12 sportsbooks...', type: 'highlight' },
    { time: '00:09', message: 'Line discrepancies found on {disc} markets — flagging for edge analysis', type: '' },
    { time: '00:10', message: 'Best line per market identified ✓', type: 'highlight' },
    { time: '00:11', message: 'All market data cached ✓', type: '' },
  ],
  intel: [
    { time: '00:12', message: 'Scanning injury reports & lineup confirmations...', type: '' },
    { time: '00:14', message: 'Scraping ESPN injury wire via Firecrawl...', type: 'highlight' },
    { time: '00:15', message: 'Found {injuries} injury updates affecting today\'s lines', type: '' },
    { time: '00:16', message: 'Cross-referencing props with injured player data...', type: 'highlight' },
    { time: '00:18', message: 'Analyzing X/Twitter sentiment by team & player...', type: '' },
    { time: '00:20', message: 'Public sentiment: 68% on favorites', type: '' },
    { time: '00:22', message: 'Sharp money tracker: {sharp} reverse line movements detected', type: 'highlight' },
    { time: '00:24', message: 'Beat reporter scan: {reporters} actionable intel updates', type: '' },
    { time: '00:25', message: 'Weather data scraped for outdoor venues ✓', type: '' },
  ],
  analyze: [
    { time: '00:26', message: 'Packaging {count} markets with intel for Claude analysis...', type: '' },
    { time: '00:27', message: 'Sending to claude-sonnet-4-20250514...', type: 'highlight' },
    { time: '00:28', message: 'Evaluating edge % on each specific market...', type: '' },
    { time: '00:30', message: 'Running Kelly Criterion unit sizing per bet...', type: '' },
    { time: '00:33', message: 'Identifying correlated bets & parlay opportunities...', type: 'highlight' },
    { time: '00:35', message: 'Cross-referencing historical trends for each bet type...', type: '' },
    { time: '00:38', message: 'Ranking by expected value — filtering sub-1% edge markets...', type: 'highlight' },
    { time: '00:40', message: 'Analysis complete — {buys} BUY signals across {types} market types', type: 'highlight' },
    { time: '00:41', message: '{props} player props · {spreads} spreads · {totals} totals · {other} other', type: '' },
    { time: '00:42', message: 'Results ready ✓', type: '' },
  ],
}

export function getMockGames(sport) {
  return MOCK_DATA[sport] || MOCK_DATA.nba
}

export function getMockLogs(stage, sport) {
  const games = getMockGames(sport)
  const uniqueGames = [...new Set(games.map(g => g.matchup))].length
  const buys = games.filter(g => g.rating === 'BUY').length
  const byes = games.filter(g => g.rating === 'BYE').length
  const props = games.filter(g => g.marketType === 'player_prop').length
  const spreads = games.filter(g => g.marketType === 'spread').length
  const totals = games.filter(g => g.marketType === 'total').length
  const other = games.length - props - spreads - totals
  const marketTypes = [...new Set(games.filter(g => g.rating === 'BUY').map(g => g.marketType))].length
  const logs = PIPELINE_LOGS[stage] || []

  return logs.map(log => ({
    ...log,
    message: log.message
      .replace('{count}', games.length)
      .replace('{games}', uniqueGames)
      .replace('{disc}', Math.floor(games.length * 0.6))
      .replace('{injuries}', 14)
      .replace('{sharp}', 3)
      .replace('{reporters}', 8)
      .replace('{buys}', buys)
      .replace('{byes}', byes)
      .replace('{types}', marketTypes)
      .replace('{props}', props)
      .replace('{spreads}', spreads)
      .replace('{totals}', totals)
      .replace('{other}', other),
  }))
}
